// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251128090937_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Domain.ConditionPhoto", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConditionDetailID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PhotoId");

                    b.HasIndex("ConditionDetailID");

                    b.ToTable("ConditionPhotos");
                });

            modelBuilder.Entity("Domain.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Domain.JobOrder", b =>
                {
                    b.Property<int>("JobOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualDateOut")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpectedDateOut")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Odometer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleID")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobOrderID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("VehicleID");

                    b.ToTable("JobOrders");
                });

            modelBuilder.Entity("Domain.JobService", b =>
                {
                    b.Property<int>("JobServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Discount")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobOrderID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceTypeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("JobServiceID");

                    b.HasIndex("JobOrderID");

                    b.HasIndex("ServiceTypeID");

                    b.ToTable("JobServices");
                });

            modelBuilder.Entity("Domain.JobServicePart", b =>
                {
                    b.Property<int>("JobServicePartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobServiceID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WarrantyMonths")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobServicePartID");

                    b.HasIndex("JobServiceID");

                    b.HasIndex("PartID");

                    b.ToTable("JobServiceParts");
                });

            modelBuilder.Entity("Domain.PaintDetail", b =>
                {
                    b.Property<int>("PaintDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaPainted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JobServiceID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LayersCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaintBrand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaintType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PaintDetailID");

                    b.HasIndex("JobServiceID")
                        .IsUnique();

                    b.ToTable("PaintDetails");
                });

            modelBuilder.Entity("Domain.Part", b =>
                {
                    b.Property<int>("PartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DefaultUnitPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PartID");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("Domain.ServiceType", b =>
                {
                    b.Property<int>("ServiceTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DefaultPrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequiresDetails")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ServiceTypeID");

                    b.ToTable("ServiceTypes");
                });

            modelBuilder.Entity("Domain.Vehicle", b =>
                {
                    b.Property<int>("VehicleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChassisNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("VehicleID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Domain.VehicleConditionDetail", b =>
                {
                    b.Property<int>("ConditionDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConditionID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasPhotos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ConditionDetailId");

                    b.HasIndex("ConditionID");

                    b.ToTable("VehicleConditionDetails");
                });

            modelBuilder.Entity("Domain.VehicleConditionHeader", b =>
                {
                    b.Property<int>("ConditionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ConditionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JobOrderID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ConditionID");

                    b.HasIndex("JobOrderID");

                    b.ToTable("VehicleConditionHeaders");
                });

            modelBuilder.Entity("Domain.ConditionPhoto", b =>
                {
                    b.HasOne("Domain.VehicleConditionDetail", "ConditionDetail")
                        .WithMany("Photos")
                        .HasForeignKey("ConditionDetailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConditionDetail");
                });

            modelBuilder.Entity("Domain.JobOrder", b =>
                {
                    b.HasOne("Domain.Customer", "Customer")
                        .WithMany("JobOrders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Vehicle", "Vehicle")
                        .WithMany("JobOrders")
                        .HasForeignKey("VehicleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Domain.JobService", b =>
                {
                    b.HasOne("Domain.JobOrder", "JobOrder")
                        .WithMany("JobServices")
                        .HasForeignKey("JobOrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.ServiceType", "ServiceType")
                        .WithMany("JobServices")
                        .HasForeignKey("ServiceTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobOrder");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("Domain.JobServicePart", b =>
                {
                    b.HasOne("Domain.JobService", "JobService")
                        .WithMany("JobServiceParts")
                        .HasForeignKey("JobServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Part", "Part")
                        .WithMany("JobServiceParts")
                        .HasForeignKey("PartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobService");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Domain.PaintDetail", b =>
                {
                    b.HasOne("Domain.JobService", "JobService")
                        .WithOne("PaintDetail")
                        .HasForeignKey("Domain.PaintDetail", "JobServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobService");
                });

            modelBuilder.Entity("Domain.Vehicle", b =>
                {
                    b.HasOne("Domain.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.VehicleConditionDetail", b =>
                {
                    b.HasOne("Domain.VehicleConditionHeader", "ConditionHeader")
                        .WithMany("ConditionDetails")
                        .HasForeignKey("ConditionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConditionHeader");
                });

            modelBuilder.Entity("Domain.VehicleConditionHeader", b =>
                {
                    b.HasOne("Domain.JobOrder", "JobOrder")
                        .WithMany("ConditionHeaders")
                        .HasForeignKey("JobOrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobOrder");
                });

            modelBuilder.Entity("Domain.Customer", b =>
                {
                    b.Navigation("JobOrders");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Domain.JobOrder", b =>
                {
                    b.Navigation("ConditionHeaders");

                    b.Navigation("JobServices");
                });

            modelBuilder.Entity("Domain.JobService", b =>
                {
                    b.Navigation("JobServiceParts");

                    b.Navigation("PaintDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Part", b =>
                {
                    b.Navigation("JobServiceParts");
                });

            modelBuilder.Entity("Domain.ServiceType", b =>
                {
                    b.Navigation("JobServices");
                });

            modelBuilder.Entity("Domain.Vehicle", b =>
                {
                    b.Navigation("JobOrders");
                });

            modelBuilder.Entity("Domain.VehicleConditionDetail", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Domain.VehicleConditionHeader", b =>
                {
                    b.Navigation("ConditionDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
